feat/nonce: allow encryption using custom nonces
maidsafe/safe_crypto pull request #24
Opened 2018-09-18 14:13 UTC by m-cat

2018-09-19 14:25 UTC, nbaksalyar requested changes

2018-09-19 14:25 UTC, nbaksalyar commented on src/lib.rs
> +    /// Convert the `SymmetricNonce` into the raw underlying bytes.
`SymmetricNonce` - probably supposed to be just `Nonce`?

2018-09-19 14:25 UTC, nbaksalyar commented on src/lib.rs
> +pub const NONCE_BYTES: usize = box_::NONCEBYTES;
Shouldn't it be `secretbox::NONCEBYTES`?

2018-09-19 14:25 UTC, nbaksalyar commented on src/lib.rs
> +    nonce: secretbox::Nonce,
A thing to note here: if this nonce is to be used for asymmetric encryption, we'll need to be sure that it's compatible with `rust_sodium::box_::Nonce`.

2018-09-19 19:24 UTC, mrcnski commented on src/lib.rs
> +    nonce: secretbox::Nonce,
I don't think we want a nonce for asymmetric encryption. Nonces are only used by symmetric encryption -- correct me if I'm wrong. I initially had a separate nonce for this case, hence the other things you pointed out, but I removed it.

Edit: I see nonces are used for precomputing a shared secret key. Should we support custom nonces for this case as well?

2018-09-20 10:47 UTC, nbaksalyar submitted a review, later dismissed

2018-10-01 20:47 UTC, m-cat commented
Closing, we merged these commits in #25

2018-10-01 20:47 UTC, closed without merging